### ISSUE TITLE
Cant deploy to vercel

### ISSUE THREAD

**Issue by Joshswooft** [QwikDev/astro#123]
Hi, I'm getting an error when I attempt to deploy an Astro + Qwik application to vercel.

npm dependencies:

```
"@astrojs/vercel": "^7.6.0",
"@builder.io/qwik": "^1.5.5",
"@builder.io/sdk-qwik": "^0.14.21",
"@qwikdev/astro": "^0.5.15",
"astro": "^4.9.1",
```

Error logs:

```
<html>
<body>
<!--StartFragment-->
Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /vercel/path0/node_modules/@builder.io/qwik/bindings/qwik.linux-x64-gnu.node)
--
18:14:53.828 | at Module._extensions..node (node:internal/modules/cjs/loader:1452:18)
18:14:53.828 | at Module.load (node:internal/modules/cjs/loader:1197:32)
18:14:53.828 | at Module._load (node:internal/modules/cjs/loader:1013:12)
18:14:53.828 | at Module.require (node:internal/modules/cjs/loader:1225:19)
18:14:53.828 | at require (node:internal/modules/helpers:177:18)
18:14:53.828 | at loadPlatformBinding (file:///vercel/path0/node_modules/@builder.io/qwik/optimizer.mjs:1371:73)
18:14:53.828 | at async createOptimizer (file:///vercel/path0/node_modules/@builder.io/qwik/optimizer.mjs:1430:48)
18:14:53.828 | at async Object.init2 [as init] (file:///vercel/path0/node_modules/@builder.io/qwik/optimizer.mjs:1824:47)
18:14:53.828 | at async config (file:///vercel/path0/node_modules/@builder.io/qwik/optimizer.mjs:3341:7)
18:14:53.828 | at async runConfigHook (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68742:25) {
18:14:53.828 | code: 'ERR_DLOPEN_FAILED'

<!--EndFragment-->
</body>
</html>

<html>
<body>
<!--StartFragment-->
QWIK ERROR Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39 s_b4nYT3DrjEk Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
--
18:14:58.615 | at createAndLogError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:42:52)
18:14:58.615 | at logErrorAndStop (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:37:57)
18:14:58.615 | at qError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:62:10)
18:14:58.615 | at serializeQRL (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3434:11)
18:14:58.615 | at file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3457:42
18:14:58.615 | at mapJoin (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3171:16)
18:14:58.615 | at serializeQRLs (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3457:10)
18:14:58.615 | at renderNode (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:850:52)
18:14:58.615 | at processData$1 (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:902:16)
18:14:58.615 | at walkChildren (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:934:12)
18:14:58.616 | Error in renderToStaticMarkup function of @qwikdev/astro:  Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
18:14:58.616 | at createAndLogError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:42:52)
18:14:58.616 | at logErrorAndStop (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:37:57)
18:14:58.616 | at qError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:62:10)
18:14:58.616 | at serializeQRL (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3434:11)
18:14:58.616 | at file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3457:42
18:14:58.616 | at mapJoin (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3171:16)
18:14:58.616 | at serializeQRLs (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3457:10)
18:14:58.617 | at renderNode (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:850:52)
18:14:58.617 | at processData$1 (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:902:16)
18:14:58.617 | at walkChildren (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:934:12)
18:14:58.618 | file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:44
18:14:58.618 | throw err;
18:14:58.618 | ^
18:14:58.618 |  
18:14:58.618 | Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
18:14:58.618 | at createAndLogError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:42:52)
18:14:58.619 | at logErrorAndStop (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:37:57)
18:14:58.619 | at qError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:62:10)
18:14:58.619 | at serializeQRL (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3434:11)
18:14:58.619 | at file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3457:42
18:14:58.619 | at mapJoin (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3171:16)
18:14:58.619 | at serializeQRLs (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:3457:10)
18:14:58.619 | at renderNode (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:850:52)
18:14:58.619 | at processData$1 (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:902:16)
18:14:58.619 | at walkChildren (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_RynSMAdE.mjs:934:12)
18:14:58.619 |  
18:14:58.619 | Node.js v18.19.1
18:14:58.654 | Error: Command "npm run build" exited with 1

<!--EndFragment-->
</body>
</html>
```

**Comment by siguici** [comment]
Hey, @Joshswooft.

You should instead report the error to [Qwik](https://github.com/QwikDev/qwik/issues/new/choose). However, the message is quite clear: "/lib64/libm.so.6: version `GLIBC_2.29' not found". I don't know your operating system but I assume it is a Unix-like system. If so, you can [try this](https://stackoverflow.com/questions/74740941/how-can-i-resolve-this-issue-libm-so-6-version-glibc-2-29 -not-found-c-c):

```bash
wget -4c https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.gz
tar -zxvf glibc-2.29.tar.gz
cd glibc-2.29
mkdir build_dir
cd build_dir
sudo ../configure --prefix=/opt/glibc
sudo make
sudo make install
```

**Comment by Joshswooft** [comment]
@siguici Thanks, I'll raise it with them. I'm using vercel so not sure how much control I have over what dependencies can be installed on their machines.

**Comment by Joshswooft** [comment]
I decided to make a small example app which highlights the problem.

Application source code is here: https://github.com/Joshswooft/fuzzy-waddle

Error:
```
<html>
<body>
<!--StartFragment-->
prerendering static routes
--
11:55:34.277 | 10:55:34 ▶ src/pages/blog/[slug].astro
11:55:34.421 | 10:55:34   ├─ /blog/my-blog-test/index.htmltitle: Blog post test 25/05/24, id: c8a0ec4edcb6404d94bb5d42da9f6f1c, isDraft: true
11:55:34.793 | Cannot resolve symbol s_b4nYT3DrjEk in { FY3ttnFVxsg: [ 's_FY3ttnFVxsg', 'q-Pc5tFKP5.js' ] }
11:55:34.794 | QWIK ERROR Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39 s_b4nYT3DrjEk Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
11:55:34.794 | at createAndLogError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:40:52)
11:55:34.794 | at logErrorAndStop (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:35:57)
11:55:34.794 | at qError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:60:10)
11:55:34.795 | at serializeQRL (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3432:11)
11:55:34.795 | at file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3455:42
11:55:34.795 | at mapJoin (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3169:16)
11:55:34.795 | at serializeQRLs (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3455:10)
11:55:34.795 | at renderNode (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:848:52)
11:55:34.795 | at processData$1 (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:900:16)
11:55:34.795 | at walkChildren (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:932:12)
11:55:34.796 | Error in renderToStaticMarkup function of @qwikdev/astro:  Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
11:55:34.796 | at createAndLogError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:40:52)
11:55:34.796 | at logErrorAndStop (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:35:57)
11:55:34.796 | at qError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:60:10)
11:55:34.796 | at serializeQRL (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3432:11)
11:55:34.796 | at file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3455:42
11:55:34.796 | at mapJoin (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3169:16)
11:55:34.796 | at serializeQRLs (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3455:10)
11:55:34.796 | at renderNode (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:848:52)
11:55:34.796 | at processData$1 (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:900:16)
11:55:34.796 | at walkChildren (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:932:12)
11:55:34.797 | file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:42
11:55:34.797 | throw err;
11:55:34.797 | ^
11:55:34.797 |  
11:55:34.797 | Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
11:55:34.797 | at createAndLogError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:40:52)
11:55:34.797 | at logErrorAndStop (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:35:57)
11:55:34.797 | at qError (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:60:10)
11:55:34.797 | at serializeQRL (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3432:11)
11:55:34.797 | at file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3455:42
11:55:34.797 | at mapJoin (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3169:16)
11:55:34.798 | at serializeQRLs (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:3455:10)
11:55:34.798 | at renderNode (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:848:52)
11:55:34.798 | at processData$1 (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:900:16)
11:55:34.798 | at walkChildren (file:///vercel/path0/.vercel/output/_functions/chunks/pages/builder-preview_BfxCJDh4.mjs:932:12)
11:55:34.798 |  
11:55:34.798 | Node.js v20.12.2
11:55:34.826 | Error: Command "npm run build" exited with 1

<!--EndFragment-->
</body>
</html>
```

**Comment by siguici** [comment]
Can you specify how to reproduce this error? Because the build works perfectly on my side:

```bash
> @0.0.1 build /home/siguici/fuzzy-waddle
> astro check && astro build

19:17:13 Types generated 249ms
19:17:13 [check] Getting diagnostics for Astro files in /home/siguici/fuzzy-waddle...
src/layouts/default.astro:16:17 - warning astro(4000): This script will be treated as if it has the `is:inline` directive because it contains an attribute. Therefore, features that require processing (e.g. using TypeScript or npm packages in the script) are unavailable.

See docs for more details: https://docs.astro.build/en/guides/client-side-scripts/#script-processing.

Add the `is:inline` directive explicitly to silence this hint.

16         <script async src="https://cdn.builder.io/js/qwik/qwikloader.js"
                   ~~~~~

Result (8 files): 
- 0 errors
- 0 warnings
- 1 hint

19:17:41 [@qwikdev/astro] astro:build:start
vite v5.2.12 building for production...
✓ 5 modules transformed.
dist/build/q-bundle-graph-le3z7r.json  0.06 kB │ gzip: 0.06 kB
dist/q-manifest.json                   1.40 kB │ gzip: 0.58 kB
dist/qwik-prefetch-service-worker.js   3.58 kB
dist/build/q-DBB_4DJj.js               0.06 kB │ gzip: 0.07 kB
dist/build/q-Pc5tFKP5.js               0.34 kB │ gzip: 0.23 kB
dist/build/q-DRazCl8O.js               5.86 kB │ gzip: 2.93 kB
✓ built in 2.07s
19:17:43 [build] output: "server"
19:17:43 [build] directory: /home/siguici/fuzzy-waddle/.vercel/output/
19:17:43 [build] adapter: @astrojs/vercel/serverless
19:17:43 [build] Collecting build info...
19:17:43 [build] ✓ Completed in 2.81s.
19:17:43 [build] Building server entrypoints...
node_modules/.pnpm/@builder.io+sdk-qwik@0.14.21_@builder.io+qwik@1.5.5_undici@6.18.1_/node_modules/@builder.io/sdk-qwik/lib/node/node-evaluate-db446d2b.js (9:25): Use of eval in "node_modules/.pnpm/@builder.io+sdk-qwik@0.14.21_@builder.io+qwik@1.5.5_undici@6.18.1_/node_modules/@builder.io/sdk-qwik/lib/node/node-evaluate-db446d2b.js" is strongly discouraged as it poses security risks and may cause issues with minification.
19:18:01 [vite] ✓ built in 18.01s
19:18:01 [build] ✓ Completed in 18.07s.

 prerendering static routes 
19:18:02 ▶ src/pages/blog/[slug].astro
[Builder.io]:  Error fetching data.  Error: Missing API key
    at generateContentUrl (file:///home/siguici/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_bEkHZWr5.mjs:13466:24)
    at fetchEntries (file:///home/siguici/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_bEkHZWr5.mjs:13540:21)
    at Module.getStaticPaths (file:///home/siguici/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_bEkHZWr5.mjs:13562:32)
    at callGetStaticPaths (file:///home/siguici/fuzzy-waddle/node_modules/.pnpm/astro@4.9.2_typescript@5.4.5/node_modules/astro/dist/core/render/route-cache.js:28:27)
    at getPathsForRoute (file:///home/siguici/fuzzy-waddle/node_modules/.pnpm/astro@4.9.2_typescript@5.4.5/node_modules/astro/dist/core/build/generate.js:200:31)
    at generatePage (file:///home/siguici/fuzzy-waddle/node_modules/.pnpm/astro@4.9.2_typescript@5.4.5/node_modules/astro/dist/core/build/generate.js:169:25)
    at async generatePages (file:///home/siguici/fuzzy-waddle/node_modules/.pnpm/astro@4.9.2_typescript@5.4.5/node_modules/astro/dist/core/build/generate.js:113:11)
    at async staticBuild (file:///home/siguici/fuzzy-waddle/node_modules/.pnpm/astro@4.9.2_typescript@5.4.5/node_modules/astro/dist/core/build/static-build.js:109:7)
    at async AstroBuilder.build (file:///home/siguici/fuzzy-waddle/node_modules/.pnpm/astro@4.9.2_typescript@5.4.5/node_modules/astro/dist/core/build/index.js:133:5)
    at async AstroBuilder.run (file:///home/siguici/fuzzy-waddle/node_modules/.pnpm/astro@4.9.2_typescript@5.4.5/node_modules/astro/dist/core/build/index.js:164:7)
19:18:02 ✓ Completed in 112ms.

19:18:02 
 finalizing server assets 

19:18:02 [build] Rearranging server assets...
19:18:02 [@astrojs/vercel/serverless] Bundling function ../../_functions/entry.mjs
19:18:04 [build] Server built in 23.81s
19:18:04 [build] Complete!
```

**Comment by Joshswooft** [comment]
@siguici There are instructions in the README on that github link I posted.

Running: `npm run astro check && npm run astro build`
Resulted in the same error i posted before:

For more context I am running node version: `v18.17.0` although this error also happens when I deploy on vercel

```
22:06:23 [@qwikdev/astro] astro:build:start
vite v5.2.11 building for production...
✓ 5 modules transformed.
dist/build/q-bundle-graph-77ig4l.json  0.06 kB │ gzip: 0.06 kB
dist/q-manifest.json                   1.34 kB │ gzip: 0.55 kB
dist/qwik-prefetch-service-worker.js   3.58 kB
dist/build/q-DBB_4DJj.js               0.06 kB │ gzip: 0.07 kB
dist/build/q-Pc5tFKP5.js               0.34 kB │ gzip: 0.23 kB
dist/build/q-DRazCl8O.js               5.86 kB │ gzip: 2.93 kB
✓ built in 332ms
22:06:23 [build] output: "server"
22:06:23 [build] directory: /home/josh/projects/fuzzy-waddle/.vercel/output/
22:06:23 [build] adapter: @astrojs/vercel/serverless
22:06:23 [build] Collecting build info...
22:06:23 [build] ✓ Completed in 520ms.
22:06:23 [build] Building server entrypoints...
node_modules/@builder.io/sdk-qwik/lib/node/node-evaluate-db446d2b.js (9:25): Use of eval in "node_modules/@builder.io/sdk-qwik/lib/node/node-evaluate-db446d2b.js" is strongly discouraged as it poses security risks and may cause issues with minification.
22:06:25 [vite] ✓ built in 2.13s
22:06:25 [build] ✓ Completed in 2.15s.

 prerendering static routes
22:06:25 ▶ src/pages/blog/[slug].astro
22:06:25   ├─ /blog/my-blog-test/index.htmltitle: Blog post test 25/05/24, id: XXXX, isDraft: true
Cannot resolve symbol s_b4nYT3DrjEk in { FY3ttnFVxsg: [ 's_FY3ttnFVxsg', 'q-Pc5tFKP5.js' ] }
QWIK ERROR Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39 s_b4nYT3DrjEk Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
    at createAndLogError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:41:52)
    at logErrorAndStop (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:36:57)
    at qError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:61:10)
    at serializeQRL (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3433:11)
    at file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3456:42
    at mapJoin (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3170:16)
    at serializeQRLs (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3456:10)
    at renderNode (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:849:52)
    at processData$1 (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:901:16)
    at walkChildren (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:933:12)
Error in renderToStaticMarkup function of @qwikdev/astro:  Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
    at createAndLogError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:41:52)
    at logErrorAndStop (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:36:57)
    at qError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:61:10)
    at serializeQRL (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3433:11)
    at file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3456:42
    at mapJoin (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3170:16)
    at serializeQRLs (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3456:10)
    at renderNode (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:849:52)
    at processData$1 (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:901:16)
    at walkChildren (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:933:12)
file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:43
    throw err;
    ^

Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
    at createAndLogError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:41:52)
    at logErrorAndStop (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:36:57)
    at qError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:61:10)
    at serializeQRL (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3433:11)
    at file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3456:42
    at mapJoin (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3170:16)
    at serializeQRLs (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:3456:10)
    at renderNode (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:849:52)
    at processData$1 (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:901:16)
    at walkChildren (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_Dy7LG7Dt.mjs:933:12)

Node.js v18.17.0
```

**Comment by siguici** [comment]
[I deployed it on Vercel successfully](https://qwik-astro-fuzzy-waddle.vercel.app):

```bash
Vercel CLI 34.2.3
? Set up and deploy “~/fuzzy-waddle”? yes
? Which scope do you want to deploy to? Sikessem
? Link to existing project? no
? What’s your project’s name? qwik-astro-fuzzy-waddle
? In which directory is your code located? ./
Local settings detected in vercel.json:
Auto-detected Project Settings (Astro):
- Build Command: astro build
- Development Command: astro dev --port $PORT
- Install Command: `yarn install`, `pnpm install`, `npm install`, or `bun install`
- Output Directory: dist
? Want to modify these settings? no
🔗  Linked to sikessem/qwik-astro-fuzzy-waddle (created .vercel)
🔍  Inspect: https://vercel.com/sikessem/qwik-astro-fuzzy-waddle/3UQRZ7cu5i1L2MGtG5P7TweUigKG [2s]
✅  Production: https://qwik-astro-fuzzy-waddle-d4adhpis5-sikessem.vercel.app [2s]
📝  Deployed to production. Run `vercel --prod` to overwrite later (https://vercel.link/2F).
💡  To change the domain or build command, go to https://vercel.com/sikessem/qwik-astro-fuzzy-waddle/settings
```

**Comment by Joshswooft** [comment]
@siguici Whats the url to the blog post? You definitely set that up as well?

**Comment by siguici** [comment]
Hey, @Joshswooft. I would like you to try this method and let us know if you get any error with Qwik:

1. Install Vercel CLI:
```bash
npm i -g vercel
```

2. Deploy on Vercel:
```bash
cd /path/to/fuzzy-waddle
vercel
```

**Comment by Joshswooft** [comment]
Updated to version : `Vercel CLI 34.2.3` (`npm i -g vercel`).

Unfortunately I still get the same error logs :(

**Comment by Joshswooft** [comment]
@siguici I've added a detailed README to the code: https://github.com/Joshswooft/fuzzy-waddle.

Please make sure you have deleted the previous project and re-cloned it then follow the setup instructions. Hopefully this time you will see the bug

**Comment by siguici** [comment]
Hi @Joshswooft.

I followed the steps that [you mentioned in https://github.com/Joshswooft/fuzzy-waddle](https://github.com/Joshswooft/fuzzy-waddle#readme) on different environments including Node@18.17.0 (as you mentioned) and Node@20.14.0 as well as with NPM and PNPM and I actually encounter the same type of error.

I hope @thejackshelton will take a look for further clarification. In the meantime, I'll take a closer look at the error on my end and see if I need to make a fix in the integration or [report the error to Qwik](https://github.com/QwikDev/qwik/issues/new/choose).

If you have any suggestions or other problems about this integration, please let us know. We will do the necessary.
Feel free to send a PR if you find a solution.

**Comment by siguici** [comment]
> I hope @thejackshelton will take a look for further clarification. In the meantime, I'll take a closer look at the error on my end and see if I need to make a fix in the integration or [report the error to Qwik](https://github.com/QwikDev/qwik/issues/new/choose).
> 
Error Message: [QRLs can not be dynamically resolved, because it does not have a chunk path](https://github.com/QwikDev/qwik/blob/7c08371480d9f2eaa7cecac4544db9dac4a546c0/packages/qwik/src/core/error/error.ts#L39)

**Comment by Joshswooft** [comment]
@thejackshelton , @siguici any update on this issue?

**Comment by Joshswooft** [comment]
Hey @thejackshelton and @siguici.

Small update from me after spending a few hours tinkering around with stuff.

If I amend the `astro.config.mjs` file to this:

```
export default defineConfig({
  integrations: [qwikdev({
    include: "./src/components/**",
  })],
  output: "server",
  adapter: vercel(),
});
```

Then the error changes to:

```
Cannot resolve symbol EnableEditor_component__Fragment_onClick_b4nYT3DrjEk in { FY3ttnFVxsg: [ 's_FY3ttnFVxsg', 'q-Pc5tFKP5.js' ] }
QWIK ERROR Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39 EnableEditor_component__Fragment_onClick_b4nYT3DrjEk Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
    at createAndLogError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:42:52)
    at logErrorAndStop (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:37:57)
    at qError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:62:10)
    at serializeQRL (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3433:11)
    at file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:42
    at mapJoin (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3171:16)
    at serializeQRLs (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:10)
    at renderNode (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:850:52)
    at processData$1 (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:902:16)
    at walkChildren (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:934:12)
Error in renderToStaticMarkup function of @qwikdev/astro:  Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
    at createAndLogError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:42:52)
    at logErrorAndStop (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:37:57)
    at qError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:62:10)
    at serializeQRL (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3433:11)
    at file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:42
    at mapJoin (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3171:16)
    at serializeQRLs (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:10)
    at renderNode (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:850:52)
    at processData$1 (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:902:16)
    at walkChildren (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:934:12)
file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:44
    throw err;
    ^

Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
    at createAndLogError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:42:52)
    at logErrorAndStop (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:37:57)
    at qError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:62:10)
    at serializeQRL (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3433:11)
    at file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:42
    at mapJoin (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3171:16)
    at serializeQRLs (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:10)
    at renderNode (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:850:52)
    at processData$1 (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:902:16)
    at walkChildren (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:934:12)

Node.js v18.17.0
```

Now when I modify the `node_modules/@qwikdev/astro/src/index.ts`

```
// ...
updateConfig({
            vite: {
              ssr: {
                external: ['@builder.io/sdk-qwik'] 
              },
              // ...
```

The project will build successfully and the website will load however the blog content served from builder.io does not render. I feel like there is a rollup/vite option that needs to be specified here 🤔 

The error above references a `EnableEditor` component: https://github.dev/BuilderIO/builder/blob/main/packages/sdks/src/components/content/components/enable-editor.lite.tsx

Which can be understood a little about here:
https://github.devBuilderIO/builder/packages/sdks/docs/ARCHITECTURE.md

**Comment by thejackshelton** [comment]
> Hey @thejackshelton and @siguici.
> 
> Small update from me after spending a few hours tinkering around with stuff.
> 
> If I amend the `astro.config.mjs` file to this:
> 
> ```
> export default defineConfig({
>   integrations: [qwikdev({
>     include: "./src/components/**",
>   })],
>   output: "server",
>   adapter: vercel(),
> });
> ```
> 
> Then the error changes to:
> 
> ```
> Cannot resolve symbol EnableEditor_component__Fragment_onClick_b4nYT3DrjEk in { FY3ttnFVxsg: [ 's_FY3ttnFVxsg', 'q-Pc5tFKP5.js' ] }
> QWIK ERROR Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39 EnableEditor_component__Fragment_onClick_b4nYT3DrjEk Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
>     at createAndLogError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:42:52)
>     at logErrorAndStop (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:37:57)
>     at qError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:62:10)
>     at serializeQRL (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3433:11)
>     at file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:42
>     at mapJoin (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3171:16)
>     at serializeQRLs (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:10)
>     at renderNode (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:850:52)
>     at processData$1 (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:902:16)
>     at walkChildren (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:934:12)
> Error in renderToStaticMarkup function of @qwikdev/astro:  Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
>     at createAndLogError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:42:52)
>     at logErrorAndStop (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:37:57)
>     at qError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:62:10)
>     at serializeQRL (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3433:11)
>     at file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:42
>     at mapJoin (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3171:16)
>     at serializeQRLs (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:10)
>     at renderNode (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:850:52)
>     at processData$1 (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:902:16)
>     at walkChildren (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:934:12)
> file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:44
>     throw err;
>     ^
> 
> Error: Code(31) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L39
>     at createAndLogError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:42:52)
>     at logErrorAndStop (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:37:57)
>     at qError (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:62:10)
>     at serializeQRL (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3433:11)
>     at file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:42
>     at mapJoin (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3171:16)
>     at serializeQRLs (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:3456:10)
>     at renderNode (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:850:52)
>     at processData$1 (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:902:16)
>     at walkChildren (file:///home/josh/projects/fuzzy-waddle/.vercel/output/_functions/chunks/prerender_M9C2GlAs.mjs:934:12)
> 
> Node.js v18.17.0
> ```
> 
> Now when I modify the `node_modules/@qwikdev/astro/src/index.ts`
> 
> ```
> // ...
> updateConfig({
>             vite: {
>               ssr: {
>                 external: ['@builder.io/sdk-qwik'] 
>               },
>               // ...
> ```
> 
> The project will build successfully and the website will load however the blog content served from builder.io does not render. I feel like there is a rollup/vite option that needs to be specified here 🤔
> 
> The error above references a `EnableEditor` component: https://github.dev/BuilderIO/builder/blob/main/packages/sdks/src/components/content/components/enable-editor.lite.tsx
> 
> Which can be understood a little about here: https://github.devBuilderIO/builder/packages/sdks/docs/ARCHITECTURE.md

Hey @Joshswooft! Yeah I'm not sure how compatible the Qwik builder sdk is with Astro. It's definitely possible they could be making an assumption of Qwik City being used, as that was previously the only meta framework used by Qwik.

This looks like a problem directly with the Builder.io CMS and Astro when using the Qwik SDK. I would bring this up on the [builder.io forum](https://forum.builder.io/)

If there is an issue directly in the integration with a minimal reproduction happy to look into it.

**Comment by thejackshelton** [comment]
@Joshswooft for the time being, I am going to close this issue. Let me know if a post is created on the builder.io forum and I can chime in.

**Comment by Joshswooft** [comment]
@thejackshelton Thanks for your reply and support for this issue. I ended up pivoting to web components for the time being as it's supported on builder.io.

When I get the chance I will follow this up on their forum and post a link here (for anyone else interested)
